return {
	-- Don't work yet
	["AlwaysGoFirst"] = false,
	["Invincible"] = false,
	["AutoUseItems"] = false,
	["AutoUseSkills"] = false,
	["AutoUseMoves"] = false,
	["AutoUseAbilities"] = false,
	["AutoUsePassives"] = false,
	["AutoUseReactions"] = false,
	
	-- Working
	["CombatSpeedMultiplier"] = 1,
	["MaxPlayerCombatSpeedMultplier"] = 2,
	["MinPlayerCombatSpeedMultplier"] = 0.5,
	
	-- Group 1
	["PlayerActionTimeLimit"] = 15,
	["POST_MOVE_DELAY"] = 1.35,
	["KILLSHOT_DELAY"] = 1.25,
	["WIND_UP_DELAY"] = 1,
	["AI_THINK_TIME"] = 0.3,
}