return {
	["Boleite Axe"] = {
		CraftingTime = 10,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 1,
			},
			{
				Name = "Rocks",
				AmountNeeded = 1,
			},
		},
		Stack = 1,
		Order = 1,
	},
	["Boleite Pickaxe"] = {
		CraftingTime = 10,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 1,
			},
			{
				Name = "Polished Boleite",
				AmountNeeded = 5,
			},
		},
		Stack = 1,
		Order = 2,
	},
	["Boleite Greatsword"] = {
		CraftingTime = 10,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 100,
			},
			{
				Name = "Polished Boleite",
				AmountNeeded = 10,
			},
		},
		Stack = 1,
		Order = 3,
	},
	["Biofuel Synthesizer"] = {
		CraftingTime = 15,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 15,
			},
			{
				Name = "Titanium",
				AmountNeeded = 10,
			},
		},
		Stack = 1,
		Order = 4,
	},
	["Mixing Pot"] = {
		CraftingTime = 8,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 5,
			},
			{
				Name = "Rocks",
				AmountNeeded = 5,
			},
			{
				Name = "Titanium",
				AmountNeeded = 10,
			},
		},
		Stack = 1,
		Order = 5,
	},
	["Wood Base"] = {
		CraftingTime = 5,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 10,
			},
		},
		Stack = 1,
		Order = 6,
	},
	["Wood Pillar"] = {
		CraftingTime = 5,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 5,
			},
		},
		Stack = 1,
		Order = 7,
	},
	["Wood Roof"] = {
		CraftingTime = 6,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 8,
			},
		},
		Stack = 1,
		Order = 8,
	},
	["Wood Stairs"] = {
		CraftingTime = 7,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 12,
			},
		},
		Stack = 1,
		Order = 9,
	},
	["Wood Wall"] = {
		CraftingTime = 6,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 10,
			},
		},
		Stack = 1,
		Order = 10,
	},
	["Wood Walldoor"] = {
		CraftingTime = 7,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 10,
			},
			{
				Name = "Titanium",
				AmountNeeded = 2,
			},
		},
		Stack = 1,
		Order = 11,
	},
	["Wooden Box"] = {
		CraftingTime = 5,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 8,
			},
		},
		Stack = 1,
		Order = 12,
	},
}
