return {
	["Woode Wheels"] = {
		CraftingPlace = "Garage",
		CraftingTime =  20,
		Materials = {
			{
				Name = "Logs",
				AmountNeeded = 25,
			},
		},
		Stack = 1,
		Order = 1,
	},
	["Boleite Wheels"] = {
		CraftingPlace = "Garage",
		CraftingTime =  20,
		Materials = {
			{
				Name = "Polished Boleite",
				AmountNeeded = 15,
			},
			{
				Name = "Logs",
				AmountNeeded = 10,
			},
		},
		Stack = 1,
		Order = 2,
	},
	["Land Vehicle Frame"] = {
		CraftingPlace = "Garage",
		CraftingTime =  20,
		Materials = {
			{
				Name = "Polished Boleite",
				AmountNeeded = 125,
			},
			{
				Name = "Logs",
				AmountNeeded = 50,
			},
			{
				Name = "Leather",
				AmountNeeded = 75,
			},
		},
		Stack = 1,
		Order = 3,
	},
	["Duney"] = {
		CraftingPlace = "Garage",
		CraftingTime = 10 ,
		Materials = {
			{
				Name = "Land Vehicle Frame",
				AmountNeeded = 125,
			},
			{
				Name = "Basic Engine",
				AmountNeeded = 50,
			},
			{
				Name = "Boleite Wheels",
				AmountNeeded = 4,
			},
		},
		Stack = 1,
		Order = 4,
	},
}