return {
	["Body"] = {
		Sub = {
			["Skin Tone"] = {
				Icon = "rbxassetid://14293315014",
				Camera = "HalfOverview",
				UIS = {
					{"Color2", ColorSequence.new{
						ColorSequenceKeypoint.new(0, Color3.new(0.101961, 0.0745098, 0.0588235)),
						ColorSequenceKeypoint.new(0.153713, Color3.new(0.184314, 0.133333, 0.109804)),
						ColorSequenceKeypoint.new(0.438687, Color3.new(0.588235, 0.372549, 0.121569)),
						ColorSequenceKeypoint.new(0.787565, Color3.new(1, 0.764706, 0.533333)),
						ColorSequenceKeypoint.new(1, Color3.new(1, 0.878431, 0.72549))},
					},
				},
				SubOrder = 1
			},
			["Race"] = {
				Icon = "rbxassetid://13734581890",
				Camera = "HalfOverview",
				UIS = {
					{"Spin", "Hairs"},
				},
				SubOrder = 2
			},
			["Hair"] = {
				Icon = "http://www.roblox.com/asset/?id=10951216726",
				Camera = "Face",
				UIS = {
					{"ItemBox", "Hair"},
					{"Color", nil},
				},
				SubOrder = 3
			},
		},
		Order = 1
	},
	["Face"] = {
		Sub = {
			["Eyes"] = {
				Icon = "rbxassetid://14293316693",
				Camera = "Face",
				UIS = {
					{"ItemBox", "Eyes"},
					{"Color2", ColorSequence.new{
						ColorSequenceKeypoint.new(0, Color3.new(0.666667, 0.333333, 0)),
						ColorSequenceKeypoint.new(0.25, Color3.new(0, 1, 0)),
						ColorSequenceKeypoint.new(0.5, Color3.new(1, 0, 0)),
						ColorSequenceKeypoint.new(0.75, Color3.new(0, 0, 1)),
						ColorSequenceKeypoint.new(1, Color3.new())}
					},
				},
				SubOrder = 1
			},
			["Mouths"] = {
				Icon = "rbxassetid://14293316360",
				Camera = "Face",
				UIS = {
					{"ItemBox", "Mouth"},
				},
				SubOrder = 2
			},
		},
		Order = 2
	},
	["Clothing"] = {
		Sub = {
			["Tops"] = {
				Icon = "rbxassetid://14293315810",
				Camera = "Top",
				UIS = {
					{"ItemBox", "Top"},
				},
				SubOrder = 1
			},
			["Bottoms"] = {
				Icon = "rbxassetid://14293316094",
				Camera = "Bottom",
				UIS = {
					{"ItemBox", "Bottom"},
				},
				SubOrder = 2
			},
			["Accessories"] = {
				Icon = "rbxassetid://14293316513",
				Camera = "HalfOverview",
				UIS = {
					{"ItemBox", "Accessories"},
				},
				SubOrder = 3
			},
		},
		Order = 3
	}
}

-- question mark free icon -> http://www.roblox.com/asset/?id=10951216726